POST http://localhost:4000/auth/register
Content-Type: application/json

{
    "username": "Bdy",
    "password": "akuBudy",
    "loginAs": "Peserta",
    "nama": "Budyyono",
    "fakultas": "Fasilkom",
    "jurusan": "Ilmu Komputer",
    "angkatan": 2022,
    "jalurMasuk": "SIMAK",
    "noKelompok": 169
}

###

POST http://localhost:4000/auth/register
Content-Type: application/json

{
    "username": "Shafa",
    "password": "akuShafa",
    "loginAs": "Mentor",
    "nama": "Shafa Najmi",
    "fakultas": "Fasilkom",
    "jurusan": "Ilmu Komputer",
    "angkatan": 2021,
    "jalurMasuk": "SIMAK",
    "noKelompok": 169
}
###
POST http://localhost:4000/auth/register
Content-Type: application/json

{
    "username": "Coda",
    "password": "akuCoda",
    "loginAs": "Mentor",
    "nama": "Tsabit Code",
    "fakultas": "Fasilkom",
    "jurusan": "Ilmu Komputer",
    "angkatan": 2022,
    "jalurMasuk": "SIMAK",
    "noKelompok": 180
}

###

DELETE http://localhost:4000/auth/delete-all

###
POST http://localhost:4000/auth/login
Content-Type: application/json

{
    "username": "Bdy",
    "password": "akuBudy"
}
###
GET http://localhost:4000/auth/get-all-mentor
###
GET http://localhost:4000/auth/get-all-peserta
###
POST http://localhost:4000/auth/login
Content-Type: application/json

{
    "username": "Shafa",
    "password": "akuShafa"
}
###
DELETE http://localhost:4000/auth/delete-all-token
###
POST http://localhost:4000/mentoring/create-mentoring
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZGRhMjYxYzlhZDUyMGEyMDdhYWJiMSIsImlhdCI6MTcwOTAyNDM2NCwiZXhwIjoxNzA5MDI1MjY0fQ.wJ96DflSnkgHlRPmHrvnNYRnUYW2n0snivM4DL7jNE4
Content-Type: application/json

{
    "lokasiMentoring": "P2",
    "passphraseAbsensi": "M2",
    "materi": "Tes2"
}
###
GET http://localhost:4000/mentoring/get-all-mentoring
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZGRhMjYxYzlhZDUyMGEyMDdhYWJiMSIsImlhdCI6MTcwOTAyNDM2NCwiZXhwIjoxNzA5MDI1MjY0fQ.wJ96DflSnkgHlRPmHrvnNYRnUYW2n0snivM4DL7jNE4
###
DELETE http://localhost:4000/auth/delete-all-meeting
###
PATCH http://localhost:4000/mentoring/isi-absensi
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZGRhMjVmYzlhZDUyMGEyMDdhYWJhYiIsImlhdCI6MTcwOTAyNDM5NSwiZXhwIjoxNzA5MDI1Mjk1fQ.kp8FhzJf8f_4KB6HdsmxsKLfymrHjJ1YNwp0el6iSKM
Content-Type: application/json

{
    "mentoringId": "65dda474ca311b18ddd5097a",
    "passphraseAbsensi": "M2"
}
###


###
POST http://localhost:4000/auth/register
Content-Type: application/json

{
    "username": "addr",
    "password": "akuAddr",
    "loginAs": "Panitia",
    "nama": "Adrian Hamzah",
    "fakultas": "Fasilkom",
    "jurusan": "Sistem Informasi",
    "angkatan": 2022,
    "tipePengurus": "PI",
    "bidangTerkait": "Koordinator Mentor",
    "jabatan": "Penanggung Jawab"
}
###
POST http://localhost:4000/auth/register
Content-Type: application/json

{
    "username": "cia",
    "password": "akuCia",
    "loginAs": "Panitia",
    "nama": "Cia123",
    "fakultas": "Fasilkom",
    "jurusan": "Sistem Informasi",
    "angkatan": 2023,
    "tipePengurus": "PI",
    "bidangTerkait": "Koordinator Mentor",
    "jabatan": "Wakil Penanggung Jawab"
}
###
GET http://localhost:4000/auth/get-all-panitia
###
POST http://localhost:4000/auth/login
Content-Type: application/json

{
    "username": "addr",
    "password": "akuAddr"
}
###
//eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZGUxNDM0MjNlMDU4YjQ1ZDMzNTVjMSIsImlhdCI6MTcwOTA1MzA1NCwiZXhwIjoxNzA5MDUzOTU0fQ.9mZn2y92qqgrw4s7osSKMgdWHjbxu5Yl1LHk5NJysfI
POST http://localhost:4000/rapat/create-rapat
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZGUxNDM0MjNlMDU4YjQ1ZDMzNTVjMSIsImlhdCI6MTcwOTA1MzA1NCwiZXhwIjoxNzA5MDUzOTU0fQ.9mZn2y92qqgrw4s7osSKMgdWHjbxu5Yl1LHk5NJysfI
Content-Type: application/json

{
    "lokasiRapat": "Balgebun",
    "kesimpulanRapat": "Coblos No 5",
    "passphraseAbsensi": "FirstRapat"
}
###
GET http://localhost:4000/rapat/get-all-rapat
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZGUxNDM0MjNlMDU4YjQ1ZDMzNTVjMSIsImlhdCI6MTcwOTA1MzA1NCwiZXhwIjoxNzA5MDUzOTU0fQ.9mZn2y92qqgrw4s7osSKMgdWHjbxu5Yl1LHk5NJysfI
//65de150d23e058b45d3355d8
###
POST http://localhost:4000/auth/login
Content-Type: application/json

{
    "username": "cia",
    "password": "akuCia"
}
//eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZGUxNDRlMjNlMDU4YjQ1ZDMzNTVjNyIsImlhdCI6MTcwOTA1MzI2MiwiZXhwIjoxNzA5MDU0MTYyfQ.y-mqyFfzQ04VgtProSmsfBomXI4ZPZiEJCSPnUg5r34
###
PATCH http://localhost:4000/rapat/isi-absensi-rapat
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZGUxNDRlMjNlMDU4YjQ1ZDMzNTVjNyIsImlhdCI6MTcwOTA1MzI2MiwiZXhwIjoxNzA5MDU0MTYyfQ.y-mqyFfzQ04VgtProSmsfBomXI4ZPZiEJCSPnUg5r34
Content-Type: application/json

{
    "rapatId": "65de150d23e058b45d3355d8",
    "passphraseAbsensi": "FirstRapat"
}